version: '3'

services:
  app:
    container_name: dev-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    depends_on:
      - database
    stdin_open: true
    tty: true
    # env_file: .env

  database:
    container_name: mysql
    restart: always
    image: mysql:latest
    ports:
      - "3309:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: binarytree
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234